name: Deploy to Heroku

on:
  workflow_dispatch:
    inputs:
      owner_id:
        description: 'Owner ID'
        required: false
        default: '1881720028'
      telegram_api:
        description: 'Telegram API'
        required: false
        default: '5310709'
      telegram_hash:
        description: 'Telegram Hash'
        required: false
        default: '63a546bdaf18e2cbba99f87b4274fa05'
      database_url:
        description: 'Database URL'
        required: false
        default: 'mongodb+srv://abcd:abcd@personalproject.mxx6dgi.mongodb.net/?retryWrites=true&w=majority'
      bot_token:
        description: 'Bot Token'
        required: false
        default: '5138249248:AAHUmRS5kBp5HlT399dtVrukHnmrdx2kfoY'
      team:
        description: 'Heroku Team'
        required: false
        default: 'tomgrp'
      heroku_app_name:
        description: 'Heroku App Name'
        required: false
        default: 'anotherdwbot3'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: 35fdd575-2627-4b9d-aeb9-bf74a73116a5
          heroku_app_name: ${{ github.event.inputs.heroku_app_name }}
          heroku_email: wuzzumva5l@zod.edu.pl
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
          team: ${{ github.event.inputs.team }}
        env:
          HD_OWNER_ID: ${{ github.event.inputs.owner_id }}
          HD_TELEGRAM_API: ${{ github.event.inputs.telegram_api }}
          HD_TELEGRAM_HASH: ${{ github.event.inputs.telegram_hash }}
          HD_DATABASE_URL: ${{ github.event.inputs.database_url }}
          HD_BOT_TOKEN: ${{ github.event.inputs.bot_token }}
          
